# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\\\n\x0c\x41\x64\x64ressModal\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\x05\x12\x12\n\nis_default\x18\x05 \x01(\x08\"\r\n\x0bUserRequest\"h\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12%\n\taddresses\x18\x04 \x03(\x0b\x32\x12.user.AddressModal2=\n\x04User\x12\x35\n\nActiveUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDRESSMODAL']._serialized_start=20
  _globals['_ADDRESSMODAL']._serialized_end=112
  _globals['_USERREQUEST']._serialized_start=114
  _globals['_USERREQUEST']._serialized_end=127
  _globals['_USERRESPONSE']._serialized_start=129
  _globals['_USERRESPONSE']._serialized_end=233
  _globals['_USER']._serialized_start=235
  _globals['_USER']._serialized_end=296
# @@protoc_insertion_point(module_scope)
