# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"3\n\x10\x41uthLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"G\n\x11\x41uthLoginResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\t\x12\x12\n\ntoken_type\x18\x03 \x01(\t\"6\n\x13\x41uthRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x14\x41uthRegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x87\x01\n\x04\x41uth\x12:\n\x05Login\x12\x16.auth.AuthLoginRequest\x1a\x17.auth.AuthLoginResponse\"\x00\x12\x43\n\x08Register\x12\x19.auth.AuthRegisterRequest\x1a\x1a.auth.AuthRegisterResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHLOGINREQUEST']._serialized_start=20
  _globals['_AUTHLOGINREQUEST']._serialized_end=71
  _globals['_AUTHLOGINRESPONSE']._serialized_start=73
  _globals['_AUTHLOGINRESPONSE']._serialized_end=144
  _globals['_AUTHREGISTERREQUEST']._serialized_start=146
  _globals['_AUTHREGISTERREQUEST']._serialized_end=200
  _globals['_AUTHREGISTERRESPONSE']._serialized_start=202
  _globals['_AUTHREGISTERRESPONSE']._serialized_end=241
  _globals['_AUTH']._serialized_start=244
  _globals['_AUTH']._serialized_end=379
# @@protoc_insertion_point(module_scope)
