# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raddress.proto\x12\x07\x61\x64\x64ress\"F\n\nAddRequest\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\x05\"\x1e\n\x0b\x41\x64\x64Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\\\n\x0c\x41\x64\x64ressModal\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\x05\x12\x12\n\nis_default\x18\x05 \x01(\x08\"\x0c\n\nGetRequest\"7\n\x0bGetResponse\x12(\n\taddresses\x18\x01 \x03(\x0b\x32\x15.address.AddressModal2q\n\x07\x41\x64\x64ress\x12\x32\n\x03\x41\x64\x64\x12\x13.address.AddRequest\x1a\x14.address.AddResponse\"\x00\x12\x32\n\x03Get\x12\x13.address.GetRequest\x1a\x14.address.GetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'address_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=26
  _globals['_ADDREQUEST']._serialized_end=96
  _globals['_ADDRESPONSE']._serialized_start=98
  _globals['_ADDRESPONSE']._serialized_end=128
  _globals['_ADDRESSMODAL']._serialized_start=130
  _globals['_ADDRESSMODAL']._serialized_end=222
  _globals['_GETREQUEST']._serialized_start=224
  _globals['_GETREQUEST']._serialized_end=236
  _globals['_GETRESPONSE']._serialized_start=238
  _globals['_GETRESPONSE']._serialized_end=293
  _globals['_ADDRESS']._serialized_start=295
  _globals['_ADDRESS']._serialized_end=408
# @@protoc_insertion_point(module_scope)
